contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    isoverridable: false
    itemVersion: 3.3.12
    packID: ""
    packName: Generic Export Indicators Service
    prevname: ""
    toServerVersion: ""
description: |-
  This playbook blocks domains using External Dynamic Link.
  The playbook adds a tag to the inputs domain indicators. the tagged domains can be publish as External Dynamic list that can be added to blocklist using products like Panorama by Palo Alto Networks.
  For Panorama - You can block the tagged domains by creating EDL(in Panorama) with the XSOAR EDL Url, and assign it to Anti-Spyware profile under "DNS Signature Policies"
adopted: true
id: 'SOC Block Domain - External Dynamic'
inputs:
- description: The domains to block
  key: Domains
  playbookInputQuery:
  required: false
  value: {}
- description: Indicator tag to assign
  key: Tag
  playbookInputQuery:
  required: false
  value: {}
name: SOC Block Domain - External Dynamic
outputs: []
quiet: true
sourceplaybookid: Block Domain - External Dynamic List
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b91dfe71-e177-4ca7-895f-1026172f5dea
      iscommand: false
      name: ""
      version: -1
    taskid: b91dfe71-e177-4ca7-895f-1026172f5dea
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Tag
          operator: isNotEmpty
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Domains
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 609eb07b-eea9-4735-83a6-3376a68b64af
      iscommand: false
      name: Use External Dynamic List?
      type: condition
      version: -1
    taskid: 609eb07b-eea9-4735-83a6-3376a68b64af
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 210
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        complex:
          root: inputs.Tag
      indicatorsValues:
        complex:
          root: inputs.Domains
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.add.values.to.indicator.multi.select.field
      id: 0aad424f-b0ce-4554-b331-e9ea121a0864
      iscommand: true
      name: Update Indicator Tag for EDL
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: 0aad424f-b0ce-4554-b331-e9ea121a0864
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 380
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bc8d3853-6554-4315-8a49-ebe6496d6160
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bc8d3853-6554-4315-8a49-ebe6496d6160
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 4842df3e-4c32-4561-8e92-17b81386b70d
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 4842df3e-4c32-4561-8e92-17b81386b70d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 550
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 730,
        "width": 671.5,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 5.0.0
