contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    isoverridable: false
    itemVersion: 2.3.11
    packID: ""
    packName: PAN-OS by Palo Alto Networks
    prevname: ""
    toServerVersion: ""
description: Commit the PAN-OS Panorama or Firewall configuration. If specified as
  Panorama, it also pushes the Policies to the specified Device Group in the instance.
adopted: true
id: 'SOC PAN-OS Commit Configuration v2'
inputs:
- description: ""
  key: device-group
  playbookInputQuery: null
  required: false
  value: {}
name: SOC PAN-OS Commit Configuration v2
outputs:
- contextPath: Panorama.Commit.JobID
  description: The job ID to commit.
- contextPath: Panorama.Commit.Status
  description: The commit status.
- contextPath: Panorama.Commit.Description
  description: The commit description from the the command input.
- contextPath: Panorama.Push.DeviceGroup
  description: The device group in which the policies were pushed.
- contextPath: Panorama.Push.JobID
  description: The job ID of the policies that were pushed.
- contextPath: Panorama.Push.Status
  description: The push status.
- contextPath: Panorama.Push.Warnings
  description: The push warnings.
- contextPath: Panorama.Push.Errors
  description: The push errors.
- contextPath: Panorama.Push.Details
  description: The job ID details.
sourceplaybookid: PAN-OS Commit Configuration v2
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 72f6ac89-7d29-48cd-8fc8-a87a469d368e
      iscommand: false
      name: ""
      version: -1
    taskid: 72f6ac89-7d29-48cd-8fc8-a87a469d368e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 585.75,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Panorama
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify that there is a valid instance of Palo Alto Networks PAN-OS
        enabled.
      id: 9c71e52d-9168-48c7-85bf-c1ed81ed2c16
      iscommand: false
      name: Is Palo Alto Networks PAN-OS enabled?
      type: condition
      version: -1
    taskid: 9c71e52d-9168-48c7-85bf-c1ed81ed2c16
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 585.75,
          "y": 210
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "20"
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      interval_in_seconds:
        simple: "60"
      polling:
        simple: "true"
      timeout:
        simple: "600"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Commit Palo Alto Firewall or Panorama
      id: 47ca3754-4567-4ccf-99b4-9f2053bb84f3
      iscommand: true
      name: Commit to Panorama
      script: '|||pan-os-commit'
      type: regular
      version: -1
    taskid: 47ca3754-4567-4ccf-99b4-9f2053bb84f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 731,
          "y": 380
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 952b0224-dd79-4eca-8721-d93bd8edd76a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 952b0224-dd79-4eca-8721-d93bd8edd76a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2250
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: errorPath
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "20"
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        complex:
          root: inputs.device-group
      interval_in_seconds:
        simple: "60"
      polling:
        simple: "true"
      timeout:
        simple: "600"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Push rules from Palo Alto Panorama to the Palo Alto configured
        device group.
      id: 0893c4a5-ca50-45fc-9ba2-d7b97a05523f
      iscommand: true
      name: Push rules to the Panorama device group
      script: '|||pan-os-push-to-device-group'
      type: regular
      version: -1
    taskid: 0893c4a5-ca50-45fc-9ba2-d7b97a05523f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 295.25,
          "y": 1570
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: errorPath
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "20"
      '#none#':
      - "14"
    note: false
    quietmode: 2
    scriptarguments:
      job_id:
        complex:
          accessor: Commit.JobID
          root: Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get commit status
      id: 11915f8b-5eca-42e1-aee9-3ec0ab14d279
      iscommand: true
      name: Get Panorama commit status
      script: '|||pan-os-commit-status'
      type: regular
      version: -1
    taskid: 11915f8b-5eca-42e1-aee9-3ec0ab14d279
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 585.75,
          "y": 550
        }
      }
  "12":
    continueonerror: true
    continueonerrortype: errorPath
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "20"
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      cmd:
        simple: <show><system><info></info></system></show>
      extend-context:
        simple: panorama.model=response.result.system.model
      type:
        simple: op
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Run any command supported in the API.
      id: c217d92e-b1cc-4713-9aa6-1f506adbe409
      iscommand: true
      name: Fetch instance info
      script: Panorama|||pan-os
      type: regular
      version: -1
    taskid: c217d92e-b1cc-4713-9aa6-1f506adbe409
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 295.25,
          "y": 1230
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: panorama.model
          operator: isEqualString
          right:
            value:
              simple: Panorama
      label: Panorama
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      Panorama:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Automatically detects the product (Panorama/Firewall).
      id: 0a67cd5e-291c-4cbf-8cf6-1898cd23ef39
      iscommand: false
      name: Identify the instance type
      type: condition
      version: -1
    taskid: 0a67cd5e-291c-4cbf-8cf6-1898cd23ef39
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1400
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Commit.Status
          operator: isEqualString
          right:
            value:
              simple: Completed
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: db94418c-0822-4d35-8bdc-6a323ac302d4
      iscommand: false
      name: Was Panorama commit successful?
      type: condition
      version: -1
    taskid: db94418c-0822-4d35-8bdc-6a323ac302d4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 440.5,
          "y": 720
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Push.Status
          operator: isEqualString
          right:
            value:
              simple: Completed
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: e5e51f27-0ef7-4603-8ff4-6f29c327187f
      iscommand: false
      name: Was Panorama push successful?
      type: condition
      version: -1
    taskid: e5e51f27-0ef7-4603-8ff4-6f29c327187f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1740
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: errorPath
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "20"
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Panorama Commit Failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 887bd879-a4dc-4870-a1fc-b07b931781e3
      iscommand: false
      name: Print commit error
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 887bd879-a4dc-4870-a1fc-b07b931781e3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 876.25,
          "y": 890
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: errorPath
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "20"
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Panorama Commit Failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 2f8737a3-3d68-449d-9756-050802e24895
      iscommand: false
      name: Print push error
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 2f8737a3-3d68-449d-9756-050802e24895
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 295.25,
          "y": 1910
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 3e46d493-9404-476d-8d95-68b8ad017a84
      iscommand: false
      name: Fix errors and commit manually
      type: regular
      version: -1
    taskid: 3e46d493-9404-476d-8d95-68b8ad017a84
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 731,
          "y": 1060
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 6e3293ac-bae0-4627-8b89-b25f67466c9f
      iscommand: false
      name: Fix errors and push manually
      type: regular
      version: -1
    taskid: 6e3293ac-bae0-4627-8b89-b25f67466c9f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 245.25,
          "y": 2080
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 8f471745-b3e3-405b-8212-4463e67e8e37
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 8f471745-b3e3-405b-8212-4463e67e8e37
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1112,
          "y": 2080
        }
      }
  "21":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: shadow_mode
          operator: isFalse
      label: "no"
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "22"
      "no":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4f19c583-8ab2-4949-a494-3821cd951d6a
      iscommand: false
      name: Shadow Run?
      type: condition
      version: -1
    taskid: 4f19c583-8ab2-4949-a494-3821cd951d6a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 234,
          "y": 358
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: 'Shadow Run: PAN-OS Commit Change'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 5ff05dbb-9158-413e-a2a4-8974c70efffd
      iscommand: false
      name: Print To WarRoom
      script: Print
      type: regular
      version: -1
    taskid: 5ff05dbb-9158-413e-a2a4-8974c70efffd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 153,
          "y": 516
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "13_5_#default#": 0.1,
      "13_6_Panorama": 0.73,
      "14_12_yes": 0.24,
      "15_17_#default#": 0.2,
      "15_5_yes": 0.1,
      "1_5_#default#": 0.17
    },
    "paper": {
      "dimensions": {
        "height": 2260,
        "width": 1443,
        "x": 50,
        "y": 50
      }
    }
  }
