adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    isoverridable: false
    itemVersion: 2.7.16
    packID: ""
    packName: SOC Common Playbooks
    prevname: ""
    supportedModules:
    - X1
    - X3
    - X5
    - ENT_PLUS
    - agentix
    toServerVersion: ""
description: |
  This playbook blocks malicious Domains using all integrations that are enabled.

  Supported integrations for this playbook:
  * Zscaler
  * Symantec Messaging Gateway
  * FireEye EX
  * Trend Micro Apex One
  * Proofpoint Threat Response
  * Cisco Stealthwatch Cloud
dirtyInputs: true
id: 'SOC Block Domain - Generic v2'
inputSections:
- description: Generic group for inputs
  inputs:
  - Domain
  - DomainBlackListID
  - Tag
  - Expiration
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: The Domain to block.
  key: Domain
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    The Domain List ID to add the Domain to.
    product: Proofpoint Threat Response
  key: DomainBlackListID
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Tag to assign Domain to the External Dynamic List.
    sub-playbook: Block Domain - External Dynamic List
  key: Tag
  playbookInputQuery: null
  required: false
  value: {}
- description: "The UTC expiration date and time of the suspicious object, for example:
    2020-01-25T09:00:00Z.\nProducts: \nTrend Micro Apex One\nProofpoint Threat Response"
  key: Expiration
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: SOC Block Domain - Generic v2
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: Block Domain - Generic v2
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
      - "16"
      - "15"
      - "14"
      - "13"
      - "12"
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 806d142e-f679-48c3-8e95-1bbc49ace64a
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 806d142e-f679-48c3-8e95-1bbc49ace64a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 160
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3c45a271-d018-4dfc-8673-429fb09bc06e
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 3c45a271-d018-4dfc-8673-429fb09bc06e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 480
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 44e7a044-1f8e-48c5-825b-349091946c05
      iscommand: false
      name: SOC Block Domain - Zscaler
      playbookId: Block Domain - Zscaler
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 44e7a044-1f8e-48c5-825b-349091946c05
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -240,
          "y": 310
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 31a3d910-b24a-44ef-8db7-44e8b3eb717d
      iscommand: false
      name: SOC Block Domain - Symantec Messaging Gateway
      playbookId: Block Domain - Symantec Messaging Gateway
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 31a3d910-b24a-44ef-8db7-44e8b3eb717d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 170,
          "y": 310
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 4d5f09d1-9911-4658-8551-ab5eba031c71
      iscommand: false
      name: SOC Block Domain - FireEye Email Security
      playbookId: Block Domain - FireEye Email Security
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 4d5f09d1-9911-4658-8551-ab5eba031c71
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 590,
          "y": 310
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 67b3f8a0-5508-45ba-8b7f-06a99eeeee0a
      iscommand: false
      name: SOC Block Domain - Trend Micro Apex One
      playbookId: Block Domain - Trend Micro Apex One
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 67b3f8a0-5508-45ba-8b7f-06a99eeeee0a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 310
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 3f71ce78-dc28-4bb2-82a5-aec91df370c6
      iscommand: false
      name: SOC Block Domain - Proofpoint Threat Response
      playbookId: Block Domain - Proofpoint Threat Response
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 3f71ce78-dc28-4bb2-82a5-aec91df370c6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1430,
          "y": 310
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 12209a16-1801-49f3-8b58-9bfc216b62d7
      iscommand: false
      name: SOC Block Domain - Cisco Stealthwatch
      playbookId: Block Domain - Cisco Stealthwatch
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 12209a16-1801-49f3-8b58-9bfc216b62d7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1850,
          "y": 310
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 8e29d096-dceb-48e5-82e6-71774d186005
      iscommand: false
      name: SOC Block Domain - External Dynamic
      playbookId: SOC Block Domain - External Dynamic
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 8e29d096-dceb-48e5-82e6-71774d186005
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2270,
          "y": 310
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 380,
        "width": 2890,
        "x": -240,
        "y": 160
      }
    }
  }
