adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    isoverridable: false
    itemVersion: 1.0.3
    packID: ""
    packName: SOC Malware Investigation Response
    prevname: ""
    supportedModules: []
    toServerVersion: ""
description: |-
  This playbook handles all the recovery actions available with Cortex XSIAM, including the following tasks:
  * Unisolate endpoint
  * Restore quarantined file

  Note: The playbook inputs enable manipulating the execution flow; read the input descriptions for details.
dirtyInputs: true
id: SOC Recovery Plan
inputSections:
- description: Generic group for inputs
  inputs:
  - unIsolateEndpoint
  - releaseFile
  - endpointID
  - FileHash
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: Set to True to cancel the endpoint isolation.
  key: unIsolateEndpoint
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
- description: Set to True to release the quarantined file.
  key: releaseFile
  playbookInputQuery: null
  required: false
  value:
    simple: "false"
- description: The endpoint ID.
  key: endpointID
  playbookInputQuery: null
  required: false
  value: {}
- description: The file hash.
  key: FileHash
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
name: SOC Recovery Plan
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: Recovery Plan
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 14722f3d-41b7-4ecd-833b-359de3d2c5b1
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 14722f3d-41b7-4ecd-833b-359de3d2c5b1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 490,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.unIsolateEndpoint
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to unisolate the endpoint.
      id: 4a47fa11-6ee1-4808-8e67-c6893fcda29f
      iscommand: false
      name: Should unisolate the endpoint?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 4a47fa11-6ee1-4808-8e67-c6893fcda29f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 220
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_id:
        complex:
          root: inputs.endpointID
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Reverses the isolation of an endpoint.
      id: 0b8c42af-b871-4e18-8f2c-bbfc5f472fd8
      iscommand: true
      name: Unisolate endpoint
      playbooktaskmissingcomponent: null
      script: '|||core-unisolate-endpoint'
      type: regular
      version: -1
    taskid: 0b8c42af-b871-4e18-8f2c-bbfc5f472fd8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 580
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f300c2f7-68b1-4368-8da4-dadd0fa6f7ab
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: f300c2f7-68b1-4368-8da4-dadd0fa6f7ab
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 765
        }
      }
  "4":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.releaseFile
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to restore the quarantined file.
      id: 08f289e7-7f40-412e-8793-409bb943c0b3
      iscommand: false
      name: Should restore the quarantined file?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 08f289e7-7f40-412e-8793-409bb943c0b3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 930,
          "y": 220
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: errorPath
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_id:
        complex:
          root: inputs.endpointID
      file_hash:
        complex:
          root: inputs.FileHash
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Restores a quarantined file on requested endpoints.
      id: a0b5fc14-cfe6-4018-8309-ddd2fe50bd05
      iscommand: true
      name: Restore file
      playbooktaskmissingcomponent: null
      script: '|||core-restore-file'
      type: regular
      version: -1
    taskid: a0b5fc14-cfe6-4018-8309-ddd2fe50bd05
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1472.5,
          "y": 580
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: c217a2c0-e628-40b8-8277-bf2ec31ef377
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: c217a2c0-e628-40b8-8277-bf2ec31ef377
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 760
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: shadow_mode
          operator: isFalse
      label: "no"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "no":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7d613c03-6dea-4175-8ae5-5e943754a11c
      iscommand: false
      name: Shadow Run?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 7d613c03-6dea-4175-8ae5-5e943754a11c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1042.5,
          "y": 400
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          Shadow Mode: XSIAM Restore File
          Command: core-restore-file
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 46029b84-aaba-4668-8a89-3333d71c57c6
      iscommand: false
      name: Print To WarRoom
      playbooktaskmissingcomponent: null
      script: Print
      type: regular
      version: -1
    taskid: 46029b84-aaba-4668-8a89-3333d71c57c6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1042.5,
          "y": 580
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: shadow_mode
          operator: isFalse
      label: "no"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "no":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ac6eba8a-4b0b-4908-8761-53054030951d
      iscommand: false
      name: Shadow Run?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: ac6eba8a-4b0b-4908-8761-53054030951d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 400
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          Shadow Mode: XSIAM Unisolate Endpoint
          Command: core-unisolate-endpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a0c8d430-394a-4de7-860f-923a75e3262e
      iscommand: false
      name: Print To WarRoom
      playbooktaskmissingcomponent: null
      script: Print
      type: regular
      version: -1
    taskid: a0c8d430-394a-4de7-860f-923a75e3262e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 580
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_3_#default#": 0.54,
      "1_9_yes": 0.9,
      "4_3_#default#": 0.54
    },
    "paper": {
      "dimensions": {
        "height": 780,
        "width": 1802.5,
        "x": 50,
        "y": 50
      }
    }
  }
