adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 2.7.15
    packID: ""
    packName: Common Playbooks
    prevname: ""
    supportedModules:
    - X1
    - X3
    - X5
    - ENT_PLUS
    - agentix
    toServerVersion: ""
description: |-
  Enrich URLs using one or more integrations.

  URL enrichment includes:
  * SSL verification for URLs.
  * Threat information.
  * Providing of URL screenshots.
  * URL Reputation using !url.
dirtyInputs: true
id: 'SOC URL Enrichment - Generic v2'
inputSections:
- description: Generic group for inputs
  inputs:
  - URL
  - Rasterize
  - VerifyURL
  - UseReputationCommand
  name: General (Inputs group)
inputs:
- description: The URLs to enrich.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
      transformers:
      - operator: uniq
- description: |-
    Define if you would like the system take safe screenshots of input URLs.
    Possible values: True / False.
    The default value is true.
  key: Rasterize
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: |-
    Define if you would like the system perform SSL certificate verification on the URLs.
    Possible values: True / False.
    The default value is false.
  key: VerifyURL
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: |-
    Define if you would like to use the !url command.
    Note: This input should be used whenever there is no auto-extract enabled in the investigation flow.
    Possible values: True / False.
    The default value is false.
  key: UseReputationCommand
  playbookInputQuery: null
  required: true
  value:
    simple: "False"
name: SOC URL Enrichment - Generic v2
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs:
  - URL
  - URL.Data
  - DBotScore
  - URL.Malicious
  - URL.Malicious.Vendor
  - URL.Malicious.Description
  - DBotScore.Indicator
  - DBotScore.Type
  - DBotScore.Vendor
  - DBotScore.Score
  - DBotScore.Reliability
  - URL.Relationships.EntityA
  - URL.Relationships.EntityB
  - URL.Relationships.Relationship
  - URL.Relationships.EntityAType
  - URL.Relationships.EntityBType
  - InfoFile.EntryID
  - InfoFile.Extension
  - InfoFile.Name
  - InfoFile.Info
  - InfoFile.Size
  - InfoFile.Type
outputs:
- contextPath: URL
  description: The URL object.
  type: uknown
- contextPath: URL.Data
  description: The enriched URL.
  type: string
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
- contextPath: URL.Malicious
  description: Whether the detected URL was malicious.
  type: unknown
- contextPath: URL.Malicious.Vendor
  description: For malicious URLs, the vendor that made the decision.
- contextPath: URL.Malicious.Description
  description: For malicious URLs, the reason that the vendor made the decision.
- contextPath: DBotScore.Indicator
  description: The indicator.
  type: string
- contextPath: DBotScore.Type
  description: The indicator's type.
  type: string
- contextPath: DBotScore.Vendor
  description: The reputation vendor.
  type: string
- contextPath: DBotScore.Score
  description: The reputation score.
  type: number
- contextPath: DBotScore.Reliability
  description: Reliability of the source providing the intelligence data.
- contextPath: URL.Relationships.EntityA
  description: The source of the relationship.
- contextPath: URL.Relationships.EntityB
  description: The destination of the relationship.
- contextPath: URL.Relationships.Relationship
  description: The name of the relationship.
- contextPath: URL.Relationships.EntityAType
  description: The type of the source of the relationship.
- contextPath: URL.Relationships.EntityBType
  description: The type of the destination of the relationship.
- contextPath: InfoFile.EntryID
  description: The EntryID of the image/pdf file.
- contextPath: InfoFile.Extension
  description: The extension of the image/pdf file.
- contextPath: InfoFile.Name
  description: The name of the image/pdf file.
- contextPath: InfoFile.Info
  description: The info of the image/pdf file.
- contextPath: InfoFile.Size
  description: The size of the image/pdf file.
- contextPath: InfoFile.Type
  description: The type of the image/pdf file.
sourceplaybookid: URL Enrichment - Generic v2
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e1a236ab-b35b-4b70-84a7-3ca08b9bbe95
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: e1a236ab-b35b-4b70-84a7-3ca08b9bbe95
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 490,
          "y": 41
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "37"
      "yes":
      - "29"
      - "31"
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there is at least one URL to enrich.
      id: 2e1b93fe-512d-4fba-80dd-2912bf3382f5
      iscommand: false
      name: Is there a URL to enrich?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 2e1b93fe-512d-4fba-80dd-2912bf3382f5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 175
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7956570c-4a34-462b-84aa-0f8c6d01cf43
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 7956570c-4a34-462b-84aa-0f8c6d01cf43
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1095
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: isEqualString
              right:
                value:
                  simple: Rasterize
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Rasterize integration
        enabled.
      id: 426d5e5a-76ec-4310-8157-e3ce1795f88f
      iscommand: false
      name: 'Is Rasterize integration enabled? '
      playbooktaskmissingcomponent: null
      script: Exists
      type: condition
      version: -1
    taskid: 426d5e5a-76ec-4310-8157-e3ce1795f88f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -40,
          "y": 710
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: errorPath
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "41"
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      execution-timeout:
        simple: "600"
      url:
        complex:
          root: inputs.URL
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rasterize
      description: Gets a screenshot of the URL page.
      id: 45ed63d2-f583-48a3-8318-92317f597f06
      iscommand: true
      name: Get URL screenshot
      playbooktaskmissingcomponent: null
      script: Rasterize|||rasterize
      tags:
      - url_screenshots
      type: regular
      version: -1
    taskid: 45ed63d2-f583-48a3-8318-92317f597f06
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -40,
          "y": 920
        }
      }
  "27":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.Rasterize
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the playbook's Rasterize input is set to "True", which
        determines whether screenshots of the URLs are created.
      id: 71af55e1-a11a-42f9-84f6-ce3ce93e17ce
      iscommand: false
      name: Capture screenshots of the URL?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 71af55e1-a11a-42f9-84f6-ce3ce93e17ce
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -40,
          "y": 500
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7fc4755c-5a08-4f90-8bab-12c892b21df4
      iscommand: false
      name: URL Screenshots
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 7fc4755c-5a08-4f90-8bab-12c892b21df4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -40,
          "y": 360
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "33"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 11224752-fee9-4a8f-82c0-5af370081779
      iscommand: false
      name: URL Verification
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 11224752-fee9-4a8f-82c0-5af370081779
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 489.5,
          "y": 360
        }
      }
  "32":
    continueonerror: true
    continueonerrortype: errorPath
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "41"
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      url:
        complex:
          root: inputs.URL
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify URL SSL certificate.
      id: 6238c2cb-a230-4546-9952-c7c51e78faf2
      iscommand: false
      name: Verify SSL for URLs
      playbooktaskmissingcomponent: null
      script: URLSSLVerification
      type: regular
      version: -1
    taskid: 6238c2cb-a230-4546-9952-c7c51e78faf2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 710
        }
      }
  "33":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.VerifyURL
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "32"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the playbook's VerifyURL input is set to "True", to determine
        whether to perform SSL verification on the URLs.
      id: 0a60d379-a6c4-449e-87e2-4939b8d0ad13
      iscommand: false
      name: Verify URLs?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 0a60d379-a6c4-449e-87e2-4939b8d0ad13
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 500
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 395ad908-d5b6-4449-8665-b085546d0d42
      iscommand: false
      name: No URLs
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 395ad908-d5b6-4449-8665-b085546d0d42
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -510,
          "y": 360
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 704516ae-95d9-4ef5-8772-1958046fcac7
      iscommand: false
      name: URL Reputation
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 704516ae-95d9-4ef5-8772-1958046fcac7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 360
        }
      }
  "39":
    continueonerror: true
    continueonerrortype: errorPath
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "41"
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      url:
        complex:
          root: inputs.URL
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Checks the reputation of a URL.
      id: 9c173500-98f2-46dd-8984-e0990a12ca73
      iscommand: true
      name: Check Reputation
      playbooktaskmissingcomponent: null
      script: '|||url'
      type: regular
      version: -1
    taskid: 9c173500-98f2-46dd-8984-e0990a12ca73
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 710
        }
      }
  "40":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UseReputationCommand
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "39"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if should run URL reputation command
      id: e0db6ab1-2c0e-4859-84eb-e764c3fd01e5
      iscommand: false
      name: Should use !url command?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: e0db6ab1-2c0e-4859-84eb-e764c3fd01e5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 500
        }
      }
  "41":
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 984fa8e7-a1bb-41f3-8980-b8fbc2556185
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 984fa8e7-a1bb-41f3-8980-b8fbc2556185
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1050,
          "y": 1090
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "25_24_#default#": 0.53,
      "25_26_yes": 0.47,
      "27_25_yes": 0.5,
      "33_24_#default#": 0.13,
      "33_32_yes": 0.67,
      "40_24_#default#": 0.31
    },
    "paper": {
      "dimensions": {
        "height": 1119,
        "width": 1940,
        "x": -510,
        "y": 41
      }
    }
  }
