adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    isoverridable: false
    itemVersion: 1.0.22
    packID: ""
    packName: Symantec Messaging Gateway
    prevname: ""
    supportedModules: []
    toServerVersion: ""
description: |-
  This playbook blocks domains using Symantec Messaging Gateway.
  The playbook checks whether the Symantec Messaging Gateway integration is enabled, whether the Domain input has been provided and if so, blocks the domain.
dirtyInputs: true
id: 'SOC Block Domain - Symantec Messaging Gateway'
inputSections:
- description: Generic group for inputs
  inputs:
  - Domain
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: The Domain to block.
  key: Domain
  playbookInputQuery:
  required: false
  value: {}
- description: ""
  key: ShadowMode
  playbookInputQuery:
  required: false
  value:
    simple: "true"
name: SOC Block Domain - Symantec Messaging Gateway
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: Block Domain - Symantec Messaging Gateway
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1ff15490-2b31-4e36-896d-faddb7a98b9d
      iscommand: false
      name: ""
      playbooktaskmissingcomponent:
      version: -1
    taskid: 1ff15490-2b31-4e36-896d-faddb7a98b9d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -210
        }
      }
  "1":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Symantec Messaging Gateway
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: Active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify that there is a valid instance of Check Point Firewall enabled.
      id: cc4526d7-39ab-42ac-8569-feb37fa265fe
      iscommand: false
      name: Is Symantec Messaging Gateway enabled?
      playbooktaskmissingcomponent:
      type: condition
      version: -1
    taskid: cc4526d7-39ab-42ac-8569-feb37fa265fe
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 680,
          "y": 80
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "5"
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
    separatecontext: false
    skipunavailable: false
    task:
      brand: Symantec Messaging Gateway
      description: Adds domain to the Local Bad Sender Domains group.
      id: 6de876c4-d943-4717-a863-bc92a9b61fb1
      iscommand: true
      name: Block Domain
      playbooktaskmissingcomponent:
      script: Symantec Messaging Gateway|||smg-block-domain
      type: regular
      version: -1
    taskid: 6de876c4-d943-4717-a863-bc92a9b61fb1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 420
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f3e2e096-cec3-4658-8bd0-517a7d4521fb
      iscommand: false
      name: Done
      playbooktaskmissingcomponent:
      type: title
      version: -1
    taskid: f3e2e096-cec3-4658-8bd0-517a7d4521fb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Domain
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the necessary inputs were provided
      id: 90796878-1467-44fd-8bf6-55a869bd827d
      iscommand: false
      name: Check if Domain input was provided
      playbooktaskmissingcomponent:
      type: condition
      version: -1
    taskid: 90796878-1467-44fd-8bf6-55a869bd827d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -80
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d37f8bb8-2a32-4ae8-8020-ba12ab0e0b59
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent:
      type: playbook
      version: -1
    taskid: d37f8bb8-2a32-4ae8-8020-ba12ab0e0b59
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1280,
          "y": 575
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Full Run:
      - "2"
      Shadow Mode:
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${inputs.ShadowMode}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7b919c34-50cd-407f-b626-b731f4650156
      iscommand: false
      name: Run Mode?
      playbooktaskmissingcomponent:
      script: ShadowModeRouter
      type: condition
      version: -1
    taskid: 7b919c34-50cd-407f-b626-b731f4650156
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 840,
          "y": 260
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          Shadow: Symantec Message Gateway Block Domain
          Command: smg-block-domain
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 311d3113-37d5-407e-bb02-449fa7bc3aaa
      iscommand: false
      name: 'Shadow: Symantec Message Gateway Block Domain'
      playbooktaskmissingcomponent:
      script: Print
      type: regular
      version: -1
    taskid: 311d3113-37d5-407e-bb02-449fa7bc3aaa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_3_#default#": 0.42,
      "4_1_yes": 0.63,
      "4_3_#default#": 0.5
    },
    "paper": {
      "dimensions": {
        "height": 855,
        "width": 1220,
        "x": 450,
        "y": -210
      }
    }
  }
fromversion: 5.0.0
