contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    isoverridable: false
    itemVersion: 2.6.55
    packID: ""
    packName: Common Playbooks
    prevname: ""
    toServerVersion: ""
description: "This playbook handles all the eradication actions available with Cortex
  XSIAM, including the following sub-playbooks:\n* Eradication Plan - Reset user password\n*
  Eradication Plan - Delete file\n* Eradication Plan - Kill process (currently, the
  playbook supports terminating a process by name)  \n\nNote: The playbook inputs
  enable manipulating the execution flow. Read the input descriptions for details."
id: 'SOC Eradication Plan'
inputs:
- description: Set to True to execute the eradication playbook automatically.
  key: AutoEradicate
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: The endpoint ID.
  key: EndpointID
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: agentid
      root: alert
- description: The file path for the file deletion and for the process termination
    task.
  key: FilePath
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: initiatorpath
      root: foundIncidents.CustomFields
- description: The username to reset the password for.
  key: Username
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: username
      root: foundIncidents.CustomFields
- description: "Choose 'Quarantine' or 'Delete'  to avoid file remediation conflicts.
    \nFor example, choosing 'Delete' ignores the 'Quarantine file' task under the
    containment playbook and executes only file deletion."
  key: FileRemediation
  playbookInputQuery: null
  required: false
  value:
    simple: Delete
- description: Set to 'True' to reset the user's password.
  key: UserRemediation
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: "Choose 'PID' to terminate the process using the Process ID, or 'Name'
    to terminate the process using its name.\nPlease note that providing the file
    path is mandatory for the process termination. \nIf 'PID' is chosen, the input
    `ProcessID` should not be empty; otherwise, the termination will not proceed."
  key: ProcessTermination
  playbookInputQuery: null
  required: false
  value:
    simple: Name
- description: The process ID to terminate.
  key: ProcessID
  playbookInputQuery: null
  required: false
  value: {}
name: SOC Eradication Plan
outputs:
- contextPath: TerminatedProcessFromEndpoints
  description: The terminated process from endpoint
  type: unknown
sourceplaybookid: Eradication Plan
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "57"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a565fd6d-2dd4-4f6f-8c41-d80d96fd1a58
      iscommand: false
      name: ""
      version: -1
    taskid: a565fd6d-2dd4-4f6f-8c41-d80d96fd1a58
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 771.5,
          "y": 50
        }
      }
  "46":
    continueonerrortype: ""
    form:
      description: Select which eradication actions to perform.
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Select Users to reset their password
        options: []
        optionsarg:
        - complex:
            root: inputs.Username
            transformers:
            - operator: uniq
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Select Files to delete
        options: []
        optionsarg:
        - complex:
            root: inputs.FilePath
            transformers:
            - operator: uniq
        placeholder: ""
        readonly: false
        required: false
        tooltip: Please consider carefully whether the file will be needed for further
          investigation before deleting it.
        type: multiSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Select Process to terminate
        options: []
        optionsarg:
        - complex:
            root: ProcessList
            transformers:
            - operator: uniq
            - args:
                applyIfEmpty: {}
                defaultValue:
                  iscontext: true
                  value:
                    simple: inputs.FilePath
              operator: SetIfEmpty
        placeholder: ""
        readonly: false
        required: false
        tooltip: Please consider carefully whether the process termination could impact
          system processes with a similar name.
        type: multiSelect
      sender: ""
      title: Which Eradication actions would you like to perform?
      totalanswers: 0
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Select which indicators to block.
      id: 0b8d21a3-7d1d-44ac-898f-f7b9dd3c484e
      iscommand: false
      name: Which eradication actions would you like to perform?
      type: collection
      version: -1
    taskid: 0b8d21a3-7d1d-44ac-898f-f7b9dd3c484e
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 916.75,
          "y": 720
        }
      }
  "47":
    continueonerrortype: ""
    id: "47"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "54"
      - "52"
      - "53"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eac14d54-acee-4628-894b-c3f85ad56381
      iscommand: false
      name: Eradication
      type: title
      version: -1
    taskid: eac14d54-acee-4628-894b-c3f85ad56381
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1012,
          "y": 890
        }
      }
  "48":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.AutoEradicate
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "46"
      "yes":
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to perform eradication actions automatically or manually.
      id: 7e62a114-2f14-44b9-8fcb-e391078f8112
      iscommand: false
      name: Should Eradicate automatically?
      type: condition
      version: -1
    taskid: 7e62a114-2f14-44b9-8fcb-e391078f8112
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1012,
          "y": 550
        }
      }
  "52":
    continueonerrortype: ""
    id: "52"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "61"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e2ca1e88-b318-4dd3-8cd0-e79bcea8b708
      iscommand: false
      name: Reset Password
      type: title
      version: -1
    taskid: e2ca1e88-b318-4dd3-8cd0-e79bcea8b708
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1493,
          "y": 1050
        }
      }
  "53":
    continueonerrortype: ""
    id: "53"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "60"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 55eece77-4b85-418a-85b4-2df675bc6406
      iscommand: false
      name: Delete File
      type: title
      version: -1
    taskid: 55eece77-4b85-418a-85b4-2df675bc6406
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1012,
          "y": 1050
        }
      }
  "54":
    continueonerrortype: ""
    id: "54"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "58"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 85a5283a-4dcb-4be9-8994-cda1836b671a
      iscommand: false
      name: Terminate Process
      type: title
      version: -1
    taskid: 85a5283a-4dcb-4be9-8994-cda1836b671a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1050
        }
      }
  "55":
    continueonerrortype: ""
    id: "55"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aca6dccc-d750-41e7-8303-cc4cb1d1e1d8
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: aca6dccc-d750-41e7-8303-cc4cb1d1e1d8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 771.5,
          "y": 1380
        }
      }
  "56":
    continueonerror: true
    continueonerrortype: errorPath
    id: "56"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "59"
      '#none#':
      - "48"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: ProcessList
      stringify:
        simple: "false"
      value:
        complex:
          root: inputs.FilePath
          transformers:
          - args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: '[^\\]+$'
              unpack_matches: {}
            operator: RegexExtractAll
          - args:
              array1_key:
                iscontext: true
              array2:
                iscontext: true
                value:
                  simple: inputs.ProcessID
              array2_key: {}
              determine_output_length_by: {}
              merge_dict: {}
              output_name1:
                value:
                  simple: Path
              output_name2:
                value:
                  simple: PID
            operator: MakePair
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: a6a87806-5c61-4c82-9c34-b01e38127473
      iscommand: false
      name: Set Process list
      script: Set
      type: regular
      version: -1
    taskid: a6a87806-5c61-4c82-9c34-b01e38127473
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 531,
          "y": 380
        }
      }
  "57":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.FilePath
          operator: isNotEmpty
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.ProcessID
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "57"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "48"
      "yes":
      - "56"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the file path and PID are defined.
      id: e5166636-3899-4c68-8dfa-b2b39ca764ed
      iscommand: false
      name: The file path and PID defined?
      type: condition
      version: -1
    taskid: e5166636-3899-4c68-8dfa-b2b39ca764ed
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 771.5,
          "y": 210
        }
      }
  "58":
    continueonerrortype: ""
    id: "58"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: f1c8bf69-c8c9-4ace-8b29-70723157ad97
      iscommand: false
      name: SOC Eradication Plan - Terminate Process
      playbookId: 'SOC Eradication Plan - Terminate Process'
      type: playbook
      version: -1
    taskid: f1c8bf69-c8c9-4ace-8b29-70723157ad97
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1210
        }
      }
  "59":
    continueonerrortype: ""
    id: "59"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 99b60fd4-2e6f-42b6-88dd-5a0398ccbbb9
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 99b60fd4-2e6f-42b6-88dd-5a0398ccbbb9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 531,
          "y": 1210
        }
      }
  "60":
    continueonerrortype: ""
    id: "60"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 60f0ccf0-52e4-4557-847a-5429ec791267
      iscommand: false
      name: SOC Eradication Plan - Delete File
      playbookId: 'SOC Eradication Plan - Delete File'
      type: playbook
      version: -1
    taskid: 60f0ccf0-52e4-4557-847a-5429ec791267
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1012,
          "y": 1210
        }
      }
  "61":
    continueonerrortype: ""
    id: "61"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d7c92058-25eb-4bdc-8109-86819f747596
      iscommand: false
      name: SOC Eradication Plan - Reset Password
      playbookId: 'SOC Eradication Plan - Reset Password'
      type: playbook
      version: -1
    taskid: d7c92058-25eb-4bdc-8109-86819f747596
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1493,
          "y": 1210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "48_47_yes": 0.53
    },
    "paper": {
      "dimensions": {
        "height": 1390,
        "width": 1824,
        "x": 50,
        "y": 50
      }
    }
  }
