adopted: true
description: This playbook will auto isolate endpoints by the device ID that was provided
  in the playbook.
dirtyInputs: true
id: 'SOC Crowdstrike Falcon - Isolate Endpoint'
inputSections:
- description: Generic group for inputs
  inputs:
  - Device_id
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: The device ID to isolate.
  key: Device_id
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: SOC Crowdstrike Falcon - Isolate Endpoint
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: Crowdstrike Falcon - Isolate Endpoint
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d0e090fd-5e1f-4b5c-82e9-eb62105b6220
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: d0e090fd-5e1f-4b5c-82e9-eb62105b6220
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: CrowdstrikeFalcon
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if the integration brand is available. Otherwise
        returns 'no'.
      id: ee96dc16-3b22-4d74-83fe-b5a86fb60115
      iscommand: false
      name: Is Crowdstrike Falcon  enabled?
      playbooktaskmissingcomponent: null
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ee96dc16-3b22-4d74-83fe-b5a86fb60115
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 44f92e5b-01a2-4070-881c-c6a931266009
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 44f92e5b-01a2-4070-881c-c6a931266009
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1760
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Device_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1fd37726-4b11-46ea-802f-46fc9e2fe715
      iscommand: false
      name: Is there Device ID?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 1fd37726-4b11-46ea-802f-46fc9e2fe715
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 810,
          "y": 490
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${inputs.Device_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CrowdstrikeFalcon
      description: Searches for a device that matches the query.
      id: 66d5a0a9-f7c9-4f23-abf4-a8ab5d888534
      iscommand: true
      name: Get device info
      playbooktaskmissingcomponent: null
      script: CrowdstrikeFalcon|||cs-falcon-search-device
      type: regular
      version: -1
    taskid: 66d5a0a9-f7c9-4f23-abf4-a8ab5d888534
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 690
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CrowdStrike.Device.Status
          operator: isEqualString
          right:
            value:
              simple: normal
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5255531d-7314-4223-8efc-ac53607d0b52
      iscommand: false
      name: Is the device ready for isolation?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 5255531d-7314-4223-8efc-ac53607d0b52
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 990,
          "y": 890
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: errorPath
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "9"
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${inputs.Device_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CrowdstrikeFalcon
      description: Contains containment for a specified host. When contained, a host
        can only communicate with the CrowdStrike cloud and any IPs specified in your
        containment policy.
      id: 8d83b1ad-dbe6-4fe7-ba1c-755241c23a84
      iscommand: true
      name: Isolate endpoint
      playbooktaskmissingcomponent: null
      script: CrowdstrikeFalcon|||cs-falcon-contain-host
      type: regular
      version: -1
    taskid: 8d83b1ad-dbe6-4fe7-ba1c-755241c23a84
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 1330
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Full Run:
      - "6"
      Shadow Mode:
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${inputs.ShadowMode}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3e9098e5-20d2-40f9-abf9-800a6900cc58
      iscommand: false
      name: Run Mode?
      playbooktaskmissingcomponent: null
      script: ShadowModeRouter
      type: condition
      version: -1
    taskid: 3e9098e5-20d2-40f9-abf9-800a6900cc58
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 990,
          "y": 1090
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          Shadow: CrowdStrike Falcon Isolate EndPoint
          Command: cs-falcon-contain-host
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e46e3518-e612-4d9b-ad76-48a9e841cc5d
      iscommand: false
      name: 'Shadow: CrowdStrike Falcon Isolate EndPoint'
      playbooktaskmissingcomponent: null
      script: Print
      type: regular
      version: -1
    taskid: e46e3518-e612-4d9b-ad76-48a9e841cc5d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1430,
          "y": 1330
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: a5744034-b39d-4989-8e3f-e891bf98b1cb
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: a5744034-b39d-4989-8e3f-e891bf98b1cb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1430,
          "y": 1755
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_2_no": 0.85,
      "3_2_#default#": 0.2,
      "3_4_yes": 0.51,
      "5_2_#default#": 0.38
    },
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 1360,
        "x": 450,
        "y": 40
      }
    }
  }
