adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 2.7.16
    packID: ""
    packName: SOC Common Playbooks
    prevname: ""
    supportedModules:
    - X1
    - X3
    - X5
    - ENT_PLUS
    - agentix
    toServerVersion: ""
description: "This playbook is used to block files from running on endpoints. \nThis
  playbook supports the following integrations:\n- Palo Alto Networks Traps\n- Palo
  Alto Networks Cortex XDR\n- Cybereason\n- Carbon Black Enterprise Response\n- Cylance
  Protect v2\n- Crowdstrike Falcon\n- Microsoft Defender for Endpoint."
dirtyInputs: true
id: 'SOC Block File - Generic v2'
inputSections:
- description: Generic group for inputs
  inputs:
  - MD5
  - SHA256
  - Hash
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: The MD5 hash of the file you want to block.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: The SHA256 hash of the file you want to block.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: In this input you can insert either MD5 or SHA256 that you wish to
    block.
  key: Hash
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: SOC Block File - Generic v2
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs:
  - CbResponse.BlockedHashes.LastBlock.Time
  - CbResponse.BlockedHashes.LastBlock.Hostname
  - CbResponse.BlockedHashes.LastBlock.CbSensorID
outputs:
- contextPath: CbResponse.BlockedHashes.LastBlock.Time
  description: Last block time.
- contextPath: CbResponse.BlockedHashes.LastBlock.Hostname
  description: Last block hostname.
- contextPath: CbResponse.BlockedHashes.LastBlock.CbSensorID
  description: Last block sensor ID.
sourceplaybookid: Block File - Generic v2
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
      - "10"
      - "11"
      - "12"
      - "17"
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 420a534c-a6e6-4cf5-8b86-ac7dd1a91441
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 420a534c-a6e6-4cf5-8b86-ac7dd1a91441
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c8476a84-8d87-4ff2-8d6c-1dd1cccc503a
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: c8476a84-8d87-4ff2-8d6c-1dd1cccc503a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 695,
          "y": 515
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 32d4b47a-e972-4e30-875b-b563130cc4ca
      iscommand: false
      name: Cybereason
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 32d4b47a-e972-4e30-875b-b563130cc4ca
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0c07d0e1-59b1-436c-8e90-f2d0410df813
      iscommand: false
      name: Carbon Black Enterprise Response
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 0c07d0e1-59b1-436c-8e90-f2d0410df813
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dcc8e191-213c-4ffd-8bc7-a8e1bc8894d7
      iscommand: false
      name: Cylance Protect v2
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: dcc8e191-213c-4ffd-8bc7-a8e1bc8894d7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b42b03dd-99c1-4149-8c32-336d23b88cf0
      iscommand: false
      name: Palo Alto Cortex XDR
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: b42b03dd-99c1-4149-8c32-336d23b88cf0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b6a4a1eb-e837-400c-890a-aa72fdd866d2
      iscommand: false
      name: CrowdStrike Falcon
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: b6a4a1eb-e837-400c-890a-aa72fdd866d2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1760,
          "y": 195
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c463f54e-7a18-4dba-804f-acf83e449259
      iscommand: false
      name: Microsoft Defender For Endpoint
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: c463f54e-7a18-4dba-804f-acf83e449259
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -380,
          "y": 195
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Hash:
        simple: ${inputs.Hash}
      'Severity ':
        simple: medium
      ShadowMode:
        simple: "true"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook receives an MD5 or a SHA256 hash and adds it to
        the block list in CrowdStrike Falcon. \nThe playbook uses the integration
        \"CrowdStrike Falcon\"."
      id: 93b14685-53e7-4a05-af58-99f2ddc4f9f7
      iscommand: false
      name: SOC CrowdStrike Falcon - Block File
      playbookId: SOC CrowdStrike Falcon - Block File
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 93b14685-53e7-4a05-af58-99f2ddc4f9f7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1760,
          "y": 330
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      GenerateAlert:
        simple: "true"
      Hash:
        complex:
          root: inputs.Hash
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.MD5
            operator: append
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.SHA256
            operator: append
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.Hash
            operator: append
          - operator: uniq
      IndicatorDescription:
        simple: Added by Cortex
      IndicatorTitle:
        simple: Added by Cortex
      ShadowMode:
        simple: "True"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook receives an MD5 or a SHA256 hash and adds it to
        the block list in Microsoft Defender for Endpoint. \nThe playbook uses the
        integration \"Microsoft Defender for Endpoint\"."
      id: c0151a75-e757-43d0-97d0-22407c890dc0
      iscommand: false
      name: SOC MDE - Block File
      playbookId: SOC MDE - Block File
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: c0151a75-e757-43d0-97d0-22407c890dc0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -380,
          "y": 340
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Use this playbook to add files to Cortex XDR block list with a
        given file SHA256 playbook input.
      id: 8552e4a4-8d86-47e5-8b7c-ee877eaf15d6
      iscommand: false
      name: SOC Cortex XDR - Block File
      playbookId: SOC Cortex XDR - Block File
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 8552e4a4-8d86-47e5-8b7c-ee877eaf15d6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 340
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This playbook receives an MD5 hash and adds it to the block list in Carbon Black Enterprise Response. Files with that MD5 hash are blocked from execution on the managed endpoints. If the hash is already on the block list, no action is taken on the MD5.

        The playbook uses the integration ''VMware Carbon Black EDR v2".
      id: ac3fa437-e615-4506-88ec-3b6afab83a58
      iscommand: false
      name: SOC Block File - Carbon Black Response
      playbookId: SOC Block File - Carbon Black Response
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: ac3fa437-e615-4506-88ec-3b6afab83a58
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 330
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 9c62ac19-3023-44af-8955-b5e2c3ea3b32
      iscommand: false
      name: SOC Block File - Cybereason
      playbookId: SOC Block File - Cybereason
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 9c62ac19-3023-44af-8955-b5e2c3ea3b32
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 330
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: c7b6c19f-c4f2-4dfd-831c-2e4fd501069b
      iscommand: false
      name: SOC Block File - Cylance Protect v2
      playbookId: SOC Block File - Cylance Protect v2
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: c7b6c19f-c4f2-4dfd-831c-2e4fd501069b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 330
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 525,
        "width": 2520,
        "x": -380,
        "y": 50
      }
    }
  }
