adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    isoverridable: false
    itemVersion: 2.7.15
    packID: ""
    packName: Common Playbooks
    prevname: ""
    supportedModules:
    - X1
    - X3
    - X5
    - ENT_PLUS
    - agentix
    toServerVersion: ""
description: "This playbook is one of the sub-playbooks in the eradication plan. \n
  The playbook executes actions to reset the user's passwords, which is a crucial
  step in the eradication process."
dirtyInputs: true
id: 'SOC Eradication Plan - Reset Password'
inputSections:
- description: Generic group for inputs
  inputs:
  - UserRemediation
  - Username
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: Set to 'True' to reset the user's password.
  key: UserRemediation
  playbookInputQuery:
  required: false
  value:
    simple: "True"
- description: The username to reset the password for.
  key: Username
  playbookInputQuery:
  required: false
  value: {}
- description: ""
  key: ShadowMode
  playbookInputQuery:
  required: false
  value:
    simple: "true"
name: SOC Eradication Plan - Reset Password
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: Eradication Plan - Reset Password
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09c31255-cc27-43a6-81db-fb416e7a41fc
      iscommand: false
      name: ""
      playbooktaskmissingcomponent:
      version: -1
    taskid: 09c31255-cc27-43a6-81db-fb416e7a41fc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -20
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "15"
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        complex:
          root: ResetPasswordToUsers
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Invalidates the password of an Active Directory user.
      id: f1dd9cb9-db2b-4b3e-8765-101a2fc3bc28
      iscommand: true
      name: Auto password reset
      playbooktaskmissingcomponent:
      script: '|||ad-expire-password'
      type: regular
      version: -1
    taskid: f1dd9cb9-db2b-4b3e-8765-101a2fc3bc28
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 910
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 83bdf4fd-82e0-41c8-801a-7dacf7cc7cb7
      iscommand: false
      name: Done
      playbooktaskmissingcomponent:
      type: title
      version: -1
    taskid: 83bdf4fd-82e0-41c8-801a-7dacf7cc7cb7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1300
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Active Directory Query v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'.
      id: ed488801-2746-4d07-8abc-1dfb26c26f70
      iscommand: false
      name: Is Active Directory Query v2 enabled?
      playbooktaskmissingcomponent:
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ed488801-2746-4d07-8abc-1dfb26c26f70
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
  "9":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UserRemediation
          operator: isEqualString
          right:
            value:
              simple: "True"
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Username
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "8"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |+
        Whether to reset the user's password based on the input values.


      id: 948a893e-2686-482c-8662-cde9931f0644
      iscommand: false
      name: Should reset the user password?
      playbooktaskmissingcomponent:
      type: condition
      version: -1
    taskid: 948a893e-2686-482c-8662-cde9931f0644
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 155
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      key:
        simple: UserPasswordReset
      value:
        complex:
          root: ResetPasswordToUsers
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: commands.local.cmd.set.parent.alert.context
      id: 11182b8c-325c-453c-8d1e-6890e1846610
      iscommand: true
      name: Set the user with a password reset to the Alert context
      playbooktaskmissingcomponent:
      script: Builtin|||setParentIncidentContext
      type: regular
      version: -1
    taskid: 11182b8c-325c-453c-8d1e-6890e1846610
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1080
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: ResetPasswordToUsers
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.Username
              operator: isNotEqualString
              right:
                value:
                  simple: Administrator
          root: inputs.Username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\n
        For more information, see the section about permissions here:\n- For Cortex
        XSOAR 6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n
        - For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      id: 89912e2c-f160-47d2-8ea0-a03d2e7125eb
      iscommand: false
      name: Set users to reset password
      playbooktaskmissingcomponent:
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 89912e2c-f160-47d2-8ea0-a03d2e7125eb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 575
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 6bd5e706-d833-4da6-850f-9060f116dcbb
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent:
      type: playbook
      version: -1
    taskid: 6bd5e706-d833-4da6-850f-9060f116dcbb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 940,
          "y": 1295
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Full Run:
      - "1"
      Shadow Mode:
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${inputs.ShadowMode}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fc1ab56a-cb19-4d9b-a11b-d9b6f9e61865
      iscommand: false
      name: Run Mode?
      playbooktaskmissingcomponent:
      script: 'ShadowModeRouter'
      type: condition
      version: -1
    taskid: fc1ab56a-cb19-4d9b-a11b-d9b6f9e61865
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          Shadow: Palo XDR Reset Password
          Command: ad-expire-password
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 3bf20258-7132-4327-8c20-54ec53cfc508
      iscommand: false
      name: 'Shadow: AD Reset Password'
      playbooktaskmissingcomponent:
      script: Print
      type: regular
      version: -1
    taskid: 3bf20258-7132-4327-8c20-54ec53cfc508
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 940,
          "y": 920
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "8_3_#default#": 0.16,
      "9_3_#default#": 0.14
    },
    "paper": {
      "dimensions": {
        "height": 1385,
        "width": 870,
        "x": 450,
        "y": -20
      }
    }
  }
fromversion: 5.0.0
