adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: 2.7.16
    packID: ""
    packName: SOC Common Playbooks
    prevname: ""
    supportedModules: []
    toServerVersion: ""
description: Chooses actions based on normalized entities and enrich them
dirtyInputs: true
id: 'SOC NIST Enrichment'
inputSections:
- description: Generic group for inputs
  inputs: []
  name: General (Inputs group)
inputs: []
name: SOC NIST Enrichment
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: auto-pb-detect-analyze-endpoint-11bcb85d-f5be-437d-a309-aeb1052386a2
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
      - "19"
      - "20"
      - "21"
      - "27"
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 27225af5-5c8c-47e1-8bc7-3b685c88f559
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 27225af5-5c8c-47e1-8bc7-3b685c88f559
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1175,
          "y": 50
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.process.hashes.sha256
          operator: isExists
          right:
            value: {}
      label: "Yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.process.hashes.sha256
          operator: isNotExists
      label: "No"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "No":
      - "22"
      "Yes":
      - "38"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Normalized.process md5/sha256.
      id: 94a9cde1-08c5-4251-8f0e-c031b77efe2d
      iscommand: false
      name: Have a Process hash?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 94a9cde1-08c5-4251-8f0e-c031b77efe2d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 390
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.host.ip
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Normalized.ip.ip
          operator: isExists
      label: "Yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.host.ip
          operator: isNotExists
      - - left:
            iscontext: true
            value:
              simple: Normalized.ip.ip
          operator: isNotExists
      label: "No"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "No":
      - "22"
      "Yes":
      - "39"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Normalized.host.ip or Normalized.ip.ip.
      id: ea3b9fc6-1814-4a30-8412-5aca97b6cd26
      iscommand: false
      name: Have an Endpoint IP?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: ea3b9fc6-1814-4a30-8412-5aca97b6cd26
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 950,
          "y": 390
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.user.user
          operator: isExists
          right:
            value: {}
      label: "Yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "22"
      "Yes":
      - "40"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Normalized.user fields for correlation.
      id: 868abdc8-4fd3-43e6-b3e4-8a8f52787af9
      iscommand: false
      name: Have a User tied to this endpoint?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 868abdc8-4fd3-43e6-b3e4-8a8f52787af9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 390
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 798b1484-152b-4136-b878-ba63d4ad8387
      iscommand: false
      name: Host Enrichent
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 798b1484-152b-4136-b878-ba63d4ad8387
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 220
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 72ccd199-d1c3-47d1-b78f-350a0c3151a5
      iscommand: false
      name: File Enrichment
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 72ccd199-d1c3-47d1-b78f-350a0c3151a5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 220
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 143681c6-6c93-4d1b-b3c1-a707aa32d15b
      iscommand: false
      name: IP Enrichment
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 143681c6-6c93-4d1b-b3c1-a707aa32d15b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 950,
          "y": 220
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4c308473-ccba-4f78-9e13-18bc1a29aac6
      iscommand: false
      name: Identity Enrichment
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 4c308473-ccba-4f78-9e13-18bc1a29aac6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 220
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b6b8b36e-2253-4433-a487-b92e0583ace6
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: b6b8b36e-2253-4433-a487-b92e0583ace6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1175,
          "y": 750
        }
      }
  "23":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.host.name
          operator: isExists
          right:
            value: {}
      label: "Yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.host.name
          operator: isNotExists
      label: "No"
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "No":
      - "22"
      "Yes":
      - "37"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Normalized.host fields.
      id: 3f6621d0-c736-482b-a04f-a4c87d287027
      iscommand: false
      name: Have a Host entity?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 3f6621d0-c736-482b-a04f-a4c87d287027
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 390
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.primary.recipients
          operator: isExists
          right:
            value: {}
      label: "Yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.primary.recipients
          operator: isNotExists
      label: "No"
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "No":
      - "22"
      "Yes":
      - "41"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Normalized.host.ip or Normalized.ip.ip.
      id: e2293a68-c616-4457-a7fc-f3a6ab04d256
      iscommand: false
      name: Have an Email?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: e2293a68-c616-4457-a7fc-f3a6ab04d256
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 2055,
          "y": 390
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 061749cd-dfd3-499f-8142-a3bce901fa48
      iscommand: false
      name: Email Enrichment
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 061749cd-dfd3-499f-8142-a3bce901fa48
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 2055,
          "y": 220
        }
      }
  "28":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.urls
          operator: isExists
          right:
            value: {}
      label: "Yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Normalized.url.url
          operator: isNotExists
      label: "No"
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "No":
      - "22"
      "Yes":
      - "42"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check Normalized.host.ip or Normalized.ip.ip.
      id: 07928f9c-77df-45ea-abd8-0154a5c0b46b
      iscommand: false
      name: Have an URL?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 07928f9c-77df-45ea-abd8-0154a5c0b46b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 2485,
          "y": 390
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ecb992e8-fbd1-48ca-a33e-fdc3387bb3e8
      iscommand: false
      name: URL Enrichment
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: ecb992e8-fbd1-48ca-a33e-fdc3387bb3e8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 2485,
          "y": 220
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: dd09d87a-9225-40a2-8df1-607b674fb4e7
      iscommand: false
      name: SOC Endpoint Enrichment - Generic v2.1
      playbookId: SOC Endpoint Enrichment - Generic v2.1
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: dd09d87a-9225-40a2-8df1-607b674fb4e7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 570
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 8990f32e-bc62-485c-8664-cec19b478952
      iscommand: false
      name: SOC File Enrichment - File reputation
      playbookId: SOC File Enrichment - File reputation
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 8990f32e-bc62-485c-8664-cec19b478952
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 500,
          "y": 570
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d1efe8ea-a699-4947-8a8b-f674a6740e7e
      iscommand: false
      name: SOC IP Enrichment - Generic v2
      playbookId: SOC IP Enrichment - Generic v2
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: d1efe8ea-a699-4947-8a8b-f674a6740e7e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 950,
          "y": 570
        }
      }
  "40":
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 5c984270-2180-4ed4-8353-50e87f8c3c84
      iscommand: false
      name: SOC Account Enrichment - Generic v2.1
      playbookId: SOC Account Enrichment - Generic v2.1
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 5c984270-2180-4ed4-8353-50e87f8c3c84
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 570
        }
      }
  "41":
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 7260f52a-6cf6-47bc-8269-96d98775f03c
      iscommand: false
      name: SOC Email Address Enrichment - Generic v2.1
      playbookId: SOC Email Address Enrichment - Generic v2.1
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 7260f52a-6cf6-47bc-8269-96d98775f03c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2055,
          "y": 570
        }
      }
  "42":
    continueonerrortype: ""
    id: "42"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: a95cc1b2-5cee-419a-898c-1c83274762e2
      iscommand: false
      name: SOC URL Enrichment - Generic v2
      playbookId: SOC URL Enrichment - Generic v2
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: a95cc1b2-5cee-419a-898c-1c83274762e2
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2485,
          "y": 570
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "23_37_Yes": 0.85,
      "26_41_Yes": 0.77,
      "28_42_Yes": 0.86,
      "5_22_No": 0.84,
      "5_39_Yes": 0.84,
      "6_40_Yes": 0.69
    },
    "paper": {
      "dimensions": {
        "height": 760,
        "width": 2815,
        "x": 50,
        "y": 50
      }
    }
  }
