adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    isoverridable: false
    itemVersion: 1.0.3
    packID: ""
    packName: SOC Malware Investigation Response
    prevname: ""
    supportedModules: []
    toServerVersion: ""
description: "This playbook handles all the eradication actions available with Cortex
  XSIAM, including the following sub-playbooks:\n* Eradication Plan - Reset user password\n*
  Eradication Plan - Delete file\n* Eradication Plan - Kill process (currently, the
  playbook supports terminating a process by name)  \n\nNote: The playbook inputs
  enable manipulating the execution flow. Read the input descriptions for details."
dirtyInputs: true
id: SOC Eradication Plan
inputSections:
- description: Generic group for inputs
  inputs:
  - AutoEradicate
  - EndpointID
  - FilePath
  - Username
  - FileRemediation
  - UserRemediation
  - ProcessTermination
  - ProcessID
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: Set to True to execute the eradication playbook automatically.
  key: AutoEradicate
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: The endpoint ID.
  key: EndpointID
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: agentid
      root: alert
- description: The file path for the file deletion and for the process termination
    task.
  key: FilePath
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: initiatorpath
      root: foundIncidents.CustomFields
- description: The username to reset the password for.
  key: Username
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: username
      root: foundIncidents.CustomFields
- description: "Choose 'Quarantine' or 'Delete'  to avoid file remediation conflicts.
    \nFor example, choosing 'Delete' ignores the 'Quarantine file' task under the
    containment playbook and executes only file deletion."
  key: FileRemediation
  playbookInputQuery: null
  required: false
  value:
    simple: Delete
- description: Set to 'True' to reset the user's password.
  key: UserRemediation
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: "Choose 'PID' to terminate the process using the Process ID, or 'Name'
    to terminate the process using its name.\nPlease note that providing the file
    path is mandatory for the process termination. \nIf 'PID' is chosen, the input
    `ProcessID` should not be empty; otherwise, the termination will not proceed."
  key: ProcessTermination
  playbookInputQuery: null
  required: false
  value:
    simple: Name
- description: The process ID to terminate.
  key: ProcessID
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
name: SOC Eradication Plan
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs:
  - TerminatedProcessFromEndpoints
outputs:
- contextPath: TerminatedProcessFromEndpoints
  description: The terminated process from endpoint
  type: unknown
sourceplaybookid: Eradication Plan
starttaskid: "0"
tags:
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "57"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8a1f8612-9c58-44a2-852c-fbb057cc5964
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 8a1f8612-9c58-44a2-852c-fbb057cc5964
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 771.5,
          "y": 50
        }
      }
  "46":
    continueonerrortype: ""
    form:
      description: Select which eradication actions to perform.
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Select Users to reset their password
        options: []
        optionsarg:
        - complex:
            root: inputs.Username
            transformers:
            - operator: uniq
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Select Files to delete
        options: []
        optionsarg:
        - complex:
            root: inputs.FilePath
            transformers:
            - operator: uniq
        placeholder: ""
        readonly: false
        required: false
        tooltip: Please consider carefully whether the file will be needed for further
          investigation before deleting it.
        type: multiSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Select Process to terminate
        options: []
        optionsarg:
        - complex:
            root: ProcessList
            transformers:
            - operator: uniq
            - args:
                applyIfEmpty: {}
                defaultValue:
                  iscontext: true
                  value:
                    simple: inputs.FilePath
              operator: SetIfEmpty
        placeholder: ""
        readonly: false
        required: false
        tooltip: Please consider carefully whether the process termination could impact
          system processes with a similar name.
        type: multiSelect
      sender: ""
      title: Which Eradication actions would you like to perform?
      totalanswers: 0
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Select which indicators to block.
      id: 95ae75f7-10c7-416d-82db-cb2767be6938
      iscommand: false
      name: Which eradication actions would you like to perform?
      playbooktaskmissingcomponent: null
      type: collection
      version: -1
    taskid: 95ae75f7-10c7-416d-82db-cb2767be6938
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 531,
          "y": 720
        }
      }
  "47":
    continueonerrortype: ""
    id: "47"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "54"
      - "52"
      - "53"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: be1183cf-bdbd-46f3-8d7c-95eb308d0770
      iscommand: false
      name: Eradication
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: be1183cf-bdbd-46f3-8d7c-95eb308d0770
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 531,
          "y": 890
        }
      }
  "48":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.AutoEradicate
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "46"
      "yes":
      - "47"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to perform eradication actions automatically or manually.
      id: 51998333-2cd0-4734-88de-323bb7949760
      iscommand: false
      name: Should Eradicate automatically?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 51998333-2cd0-4734-88de-323bb7949760
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 531,
          "y": 550
        }
      }
  "52":
    continueonerrortype: ""
    id: "52"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "61"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f3bdd4a7-1f37-4dcb-817c-faf569aeb63c
      iscommand: false
      name: Reset Password
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: f3bdd4a7-1f37-4dcb-817c-faf569aeb63c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1050
        }
      }
  "53":
    continueonerrortype: ""
    id: "53"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "60"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9bd8bd88-06d7-445c-8e01-89cea2a86c49
      iscommand: false
      name: Delete File
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 9bd8bd88-06d7-445c-8e01-89cea2a86c49
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 531,
          "y": 1050
        }
      }
  "54":
    continueonerrortype: ""
    id: "54"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "58"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2272fb0f-3155-45e9-8614-e232f881b3f0
      iscommand: false
      name: Terminate Process
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 2272fb0f-3155-45e9-8614-e232f881b3f0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1012,
          "y": 1050
        }
      }
  "55":
    continueonerrortype: ""
    id: "55"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fba37ccc-45a8-44d3-86e8-98749a41ee98
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: fba37ccc-45a8-44d3-86e8-98749a41ee98
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 290.5,
          "y": 1380
        }
      }
  "56":
    continueonerror: true
    continueonerrortype: errorPath
    id: "56"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "59"
      '#none#':
      - "48"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: ProcessList
      stringify:
        simple: "false"
      value:
        complex:
          root: inputs.FilePath
          transformers:
          - args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: '[^\\]+$'
              unpack_matches: {}
            operator: RegexExtractAll
          - args:
              array1_key:
                iscontext: true
              array2:
                iscontext: true
                value:
                  simple: inputs.ProcessID
              array2_key: {}
              determine_output_length_by: {}
              merge_dict: {}
              output_name1:
                value:
                  simple: Path
              output_name2:
                value:
                  simple: PID
            operator: MakePair
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: e0ee716d-efb5-4568-8927-016c88b3c60c
      iscommand: false
      name: Set Process list
      playbooktaskmissingcomponent: null
      script: Set
      type: regular
      version: -1
    taskid: e0ee716d-efb5-4568-8927-016c88b3c60c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 962,
          "y": 380
        }
      }
  "57":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.FilePath
          operator: isNotEmpty
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.ProcessID
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "57"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "48"
      "yes":
      - "56"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the file path and PID are defined.
      id: 05e399ac-c959-4ccc-8f81-1f90461da779
      iscommand: false
      name: The file path and PID defined?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 05e399ac-c959-4ccc-8f81-1f90461da779
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 771.5,
          "y": 210
        }
      }
  "58":
    continueonerrortype: ""
    id: "58"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    scriptarguments:
      ProcessTermination:
        simple: Name
      ShadowMode:
        simple: ${inputs.ShadowMode}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook is one of the sub-playbooks in the eradication plan.
        \nThis playbook handles the termination of the processes as a crucial step
        in the eradication action.\nThe playbook executes actions of process termination,
        which is a crucial step in the eradication process.\nThe process termination
        can be performed based on either the process ID or the process name."
      id: d6fb7354-da20-4845-8d27-34cc5c934754
      iscommand: false
      name: SOC Eradication Plan - Terminate Process
      playbookId: SOC Eradication Plan - Terminate Process
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: d6fb7354-da20-4845-8d27-34cc5c934754
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1012,
          "y": 1210
        }
      }
  "59":
    continueonerrortype: ""
    id: "59"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 1a454fc4-4479-4a5b-879e-79c16e5eba52
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 1a454fc4-4479-4a5b-879e-79c16e5eba52
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1012,
          "y": 550
        }
      }
  "60":
    continueonerrortype: ""
    id: "60"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    scriptarguments:
      EndpointID:
        complex:
          root: Endpoints
      FilePath:
        complex:
          root: Path
      FileRemediation:
        simple: Delete
      ShadowMode:
        simple: ${inputs.ShadowMode}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook is one of the sub-playbooks in the eradication plan.
        \nThis playbook executes actions of file deletion, which is a crucial step
        in the eradication process."
      id: 15bdf486-8310-45b6-86b4-5fcc7af0448e
      iscommand: false
      name: SOC Eradication Plan - Delete File
      playbookId: SOC Eradication Plan - Delete File
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 15bdf486-8310-45b6-86b4-5fcc7af0448e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 531,
          "y": 1210
        }
      }
  "61":
    continueonerrortype: ""
    id: "61"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "55"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${inputs.ShadowMode}
      UserRemediation:
        simple: "True"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook is one of the sub-playbooks in the eradication plan.
        \nThe playbook executes actions to reset the user's passwords, which is a
        crucial step in the eradication process."
      id: a934bf01-a2bf-4e90-85f4-dd253089dd9b
      iscommand: false
      name: SOC Eradication Plan - Reset Password
      playbookId: SOC Eradication Plan - Reset Password
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: a934bf01-a2bf-4e90-85f4-dd253089dd9b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "48_47_yes": 0.53
    },
    "paper": {
      "dimensions": {
        "height": 1390,
        "width": 1342,
        "x": 50,
        "y": 50
      }
    }
  }
