contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    isoverridable: false
    itemVersion: 1.0.0
    packID: ""
    packName: SOC Common Playbooks
    prevname: ""
    toServerVersion: ""
description: "This playbook is one of the sub-playbooks in the eradication plan. \nThis
  playbook executes actions of file deletion, which is a crucial step in the eradication
  process."
dirtyInputs: true
id: 'SOC Eradication Plan - Delete File'
inputSections:
- description: Generic group for inputs
  inputs:
  - FileRemediation
  - EndpointID
  - FilePath
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: "Choose 'Quarantine' or 'Delete' to avoid file remediation conflicts.
    \nFor example, choosing 'Delete' ignores the 'Quarantine file' task under the
    containment playbook and executes only file deletion."
  key: FileRemediation
  playbookInputQuery: null
  required: false
  value:
    simple: Delete
- description: The endpoint ID.
  key: EndpointID
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: Endpoints
- description: The file path for the file deletion task.
  key: FilePath
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: Path
- description: Shadow Mode is a key safety mechanism. It ensures actions like isolate_endpoint
    or disable_user are logged but not executed in test scenarios.
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: SOC Eradication Plan - Delete File
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: Eradication Plan - Delete File
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 48cbb13a-a0c0-4a27-815a-66e38f3387ff
      iscommand: false
      name: ""
      version: -1
    taskid: 48cbb13a-a0c0-4a27-815a-66e38f3387ff
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 631,
          "y": 50
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "22"
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_ids:
        complex:
          root: inputs.EndpointID
      file_path:
        complex:
          root: inputs.FilePath
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Initiates a new endpoint script execution to delete the specified
        file.
      id: bf5564c9-a811-4c12-8beb-682092e6a29d
      iscommand: true
      name: Auto file deletion
      script: '|||core-run-script-delete-file'
      type: regular
      version: -1
    taskid: bf5564c9-a811-4c12-8beb-682092e6a29d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 776.25,
          "y": 550
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 040279ae-6f3d-42a1-8def-2c0565fd669f
      iscommand: false
      name: Done - File Deletion
      type: title
      version: -1
    taskid: 040279ae-6f3d-42a1-8def-2c0565fd669f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 895
        }
      }
  "19":
    continueonerror: true
    continueonerrortype: errorPath
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "22"
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      action_id:
        complex:
          accessor: action_id
          root: Core.GetActionStatus
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve the results of a script execution action.
      id: 4d6ce008-7437-4c99-b027-a359553f2b09
      iscommand: true
      name: Get command result
      script: '|||core-get-script-execution-results'
      type: regular
      version: -1
    taskid: 4d6ce008-7437-4c99-b027-a359553f2b09
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 631,
          "y": 720
        }
      }
  "21":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.FilePath
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.EndpointID
          operator: isNotEmpty
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.FileRemediation
          operator: isEqualString
          right:
            value:
              simple: Delete
      label: "yes"
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to delete the file based on the input values.
      id: a1a09dd3-d1de-40ae-898b-6fe92bd93c6e
      iscommand: false
      name: Should delete the file?
      type: condition
      version: -1
    taskid: a1a09dd3-d1de-40ae-898b-6fe92bd93c6e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 631,
          "y": 210
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 48a372ef-38cb-49a1-b1fc-23ecc648094b
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 48a372ef-38cb-49a1-b1fc-23ecc648094b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 871.5,
          "y": 890
        }
      }
  "23":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ShadowMode
          operator: isFalse
          right:
            value: {}
      label: "no"
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "no":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8c55417c-e150-4336-b9f3-e3d8a9931845
      iscommand: false
      name: Shadow Run?
      type: condition
      version: -1
    taskid: 8c55417c-e150-4336-b9f3-e3d8a9931845
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 776.25,
          "y": 380
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          Shadow Mode: XSIAM Auto File Deletion
          Command: core-run-script-delete
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 979a62b5-b940-46f1-83dc-328d32d8138b
      iscommand: false
      name: Print To WarRoom
      script: Print
      type: regular
      version: -1
    taskid: 979a62b5-b940-46f1-83dc-328d32d8138b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 1201.5,
        "x": 50,
        "y": 50
      }
    }
  }
adopted: true