contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    isoverridable: false
    itemVersion: 1.0.0
    packID: ""
    packName: SOC Common Playbooks
    prevname: ""
    toServerVersion: ""
description: |-
  ## Containment Plan - Disable Account

  This playbook is a sub-playbook within the containment plan playbook.
  The playbook disables users by utilizing the sub-playbook "Block Account - Generic v2"
id: 'SOC Containment Plan - Disable Account'
inputs:
- description: Set to 'True' to disable the user account.
  key: UserContainment
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: The username to disable.
  key: Username
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Possible values:True/False. Default:True.
    Specify if User Verification is required to disable users.
  key: UserVerification
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
name: SOC Containment Plan - Disable Account
outputs:
- contextPath: Blocklist.Final
  description: Blocked accounts
  type: unknown
quiet: true
sourceplaybookid: Containment Plan - Disable Account
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9fb1ed1d-c22c-48bb-8a3c-4d58bbca6347
      iscommand: false
      name: ""
      version: -1
    taskid: 9fb1ed1d-c22c-48bb-8a3c-4d58bbca6347
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4d874c50-7a1f-489c-8397-3fc3304eeea6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4d874c50-7a1f-489c-8397-3fc3304eeea6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: errorPath
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "19"
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: UsersBlockList
      value:
        complex:
          accessor: Final
          root: Blocklist
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: commands.local.cmd.set.parent.alert.context
      id: 0cd4f12b-8840-4d35-ae5a-e6b78e2b9d06
      iscommand: true
      name: Set disabled users to the Alert context
      script: Builtin|||setParentIncidentContext
      type: regular
      version: -1
    taskid: 0cd4f12b-8840-4d35-ae5a-e6b78e2b9d06
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 720
        }
      }
  "12":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UserContainment
          operator: isEqualString
          right:
            value:
              simple: "True"
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Username
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to disable the account based on the input values.
      id: 073f607c-a924-43c1-8852-d480e1454fdc
      iscommand: false
      name: Should disable the account?
      type: condition
      version: -1
    taskid: 073f607c-a924-43c1-8852-d480e1454fdc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 210
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: errorPath
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "19"
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: UsersToDisable
      value:
        complex:
          root: inputs.Username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\nFor
        more information, see the section about permissions here:\n- For Cortex see
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      id: bed0b1e1-e71f-4947-a7d6-4c97d6e5bcd6
      iscommand: false
      name: Set users to disable
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: bed0b1e1-e71f-4947-a7d6-4c97d6e5bcd6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 380
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 396c5310-aca1-4a2d-862c-926e3568e60f
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 396c5310-aca1-4a2d-862c-926e3568e60f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 890
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${shadow_mode}
      Tag:
        simple: Bad Account
      UserVerification:
        simple: "True"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: dfba142c-0ea4-4492-9730-27e1713d893d
      iscommand: false
      name: SOC Block Account - Generic v2_copy
      playbookId: 'SOC Block Account - Generic v2_copy'
      type: playbook
      version: -1
    taskid: dfba142c-0ea4-4492-9730-27e1713d893d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 550
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "12_2_#default#": 0.16
    },
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 922.5,
        "x": 50,
        "y": 50
      }
    }
  }
