contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: 1.0.0
    packID: ""
    packName: SOC Malware Investigation Response
    prevname: ""
    toServerVersion: ""
id: 'SOC Malware Investigation and Response'
inputs: []
name: SOC Malware Investigation and Response
outputs: []
quiet: true
sourceplaybookid: SOC Malware Investigation and Response
starttaskid: "0"
tags:
- PoV
- Malware
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f75b83db-28cb-498c-8af1-613cc6acea94
      iscommand: false
      name: ""
      version: -1
    taskid: f75b83db-28cb-498c-8af1-613cc6acea94
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 04b59572-47e7-49d8-a6bf-4f7ec319ae51
      iscommand: false
      name: SOC Optimization
      type: title
      version: -1
    taskid: 04b59572-47e7-49d8-a6bf-4f7ec319ae51
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0e13ef77-364d-473c-bfac-c7abbb0e9006
      iscommand: false
      name: Enrichment
      type: title
      version: -1
    taskid: 0e13ef77-364d-473c-bfac-c7abbb0e9006
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 540
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 78c2b431-2745-4254-819f-2bc2b4abe7d4
      iscommand: false
      name: Containment
      type: title
      version: -1
    taskid: 78c2b431-2745-4254-819f-2bc2b4abe7d4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1210
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 33604eef-62ff-4b0a-b7af-12e5e96a0765
      iscommand: false
      name: Eradication
      type: title
      version: -1
    taskid: 33604eef-62ff-4b0a-b7af-12e5e96a0765
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: baf524eb-d52e-4ee9-bee1-bb64e87a86ea
      iscommand: false
      name: Recovery
      type: title
      version: -1
    taskid: baf524eb-d52e-4ee9-bee1-bb64e87a86ea
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2040
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b1c4bdd3-89cd-45fd-b9e0-8f545de57d6a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b1c4bdd3-89cd-45fd-b9e0-8f545de57d6a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2370
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      id: 46aa4f97-b564-469a-8a5a-2200cf7cd447
      iscommand: false
      name: Foundation - Upon Trigger
      playbookId: Foundation - Upon Trigger
      type: playbook
      version: -1
    taskid: 46aa4f97-b564-469a-8a5a-2200cf7cd447
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 2e587f06-2bb4-4a8a-8dd8-213b3679597a
      iscommand: false
      name: SOC Handle False Positive Alerts
      playbookId: SOC Handle False Positive Alerts
      type: playbook
      version: -1
    taskid: 2e587f06-2bb4-4a8a-8dd8-213b3679597a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1370
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 0fd14263-9af9-4be7-84cc-8cb7f313a777
      iscommand: false
      name: SOC Enrichment for Verdict
      playbookId: SOC Enrichment for Verdict
      type: playbook
      version: -1
    taskid: 0fd14263-9af9-4be7-84cc-8cb7f313a777
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 700
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: b75918d0-7372-4b47-8ae0-7c82a8c5fdb6
      iscommand: false
      name: SOC Wildfire Detonate and Analyze
      playbookId: SOC Wildfire Detonate and Analyze
      type: playbook
      version: -1
    taskid: b75918d0-7372-4b47-8ae0-7c82a8c5fdb6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 870
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 168dc6b0-d589-47fb-8552-ed53025c3381
      iscommand: false
      name: SOC Endpoint Investigation Plan
      playbookId: SOC Endpoint Investigation Plan
      type: playbook
      version: -1
    taskid: 168dc6b0-d589-47fb-8552-ed53025c3381
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d20f950f-67e9-4a02-8f8b-bd5148b832ba
      iscommand: false
      name: SOC Containment Plan
      playbookId: SOC Containment Plan
      type: playbook
      version: -1
    taskid: d20f950f-67e9-4a02-8f8b-bd5148b832ba
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1540
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 038fee5b-b188-4c96-8a76-119ddd4486c1
      iscommand: false
      name: SOC Eradication Plan
      playbookId: SOC Eradication Plan
      type: playbook
      version: -1
    taskid: 038fee5b-b188-4c96-8a76-119ddd4486c1
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1870
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d3720bbe-edcc-4dfe-81e2-a481d9e36824
      iscommand: false
      name: SOC Recovery Plan
      playbookId: SOC Recovery Plan
      type: playbook
      version: -1
    taskid: d3720bbe-edcc-4dfe-81e2-a481d9e36824
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2200
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2380,
        "width": 381,
        "x": 50,
        "y": 50
      }
    }
  }
