contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.6.0
    isoverridable: false
    itemVersion: 1.0.0
    packID: ""
    packName: SOC Common Playbooks
    prevname: ""
    toServerVersion: ""
description: "This playbook is one of the sub-playbooks in the eradication plan. \nThe
  playbook executes actions to reset the user's passwords, which is a crucial step
  in the eradication process."
id: 'SOC Eradication Plan - Reset Password'
inputs:
- description: Set to 'True' to reset the user's password.
  key: UserRemediation
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: The username to reset the password for.
  key: Username
  playbookInputQuery: null
  required: false
  value: {}
name: SOC Eradication Plan - Reset Password
outputs: []
sourceplaybookid: Eradication Plan - Reset Password
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09c31255-cc27-43a6-81db-fb416e7a41fc
      iscommand: false
      name: ""
      version: -1
    taskid: 09c31255-cc27-43a6-81db-fb416e7a41fc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "15"
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        complex:
          root: ResetPasswordToUsers
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Invalidates the password of an Active Directory user.
      id: dfeaef51-c21f-421c-bde3-fd02f366bfae
      iscommand: true
      name: Auto password reset
      script: '|||ad-expire-password'
      type: regular
      version: -1
    taskid: dfeaef51-c21f-421c-bde3-fd02f366bfae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1257.25,
          "y": 890
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 83bdf4fd-82e0-41c8-801a-7dacf7cc7cb7
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 83bdf4fd-82e0-41c8-801a-7dacf7cc7cb7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 390.5,
          "y": 1235
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Active Directory Query v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'.
      id: ed488801-2746-4d07-8abc-1dfb26c26f70
      iscommand: false
      name: Is Active Directory Query v2 enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ed488801-2746-4d07-8abc-1dfb26c26f70
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 380
        }
      }
  "9":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UserRemediation
          operator: isEqualString
          right:
            value:
              simple: "True"
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Username
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "8"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |+
        Whether to reset the user's password based on the input values.


      id: 948a893e-2686-482c-8662-cde9931f0644
      iscommand: false
      name: Should reset the user password?
      type: condition
      version: -1
    taskid: 948a893e-2686-482c-8662-cde9931f0644
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: errorPath
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "15"
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      key:
        simple: UserPasswordReset
      value:
        complex:
          root: ResetPasswordToUsers
    separatecontext: false
    skipunavailable: true
    task:
      brand: Builtin
      description: commands.local.cmd.set.parent.alert.context
      id: b4155a5b-a3c5-4b36-a690-3efaf2702afc
      iscommand: true
      name: Set the user with a password reset to the Alert context
      script: Builtin|||setParentIncidentContext
      type: regular
      version: -1
    taskid: b4155a5b-a3c5-4b36-a690-3efaf2702afc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1112,
          "y": 1060
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: errorPath
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "15"
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: ResetPasswordToUsers
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: inputs.Username
              operator: isNotEqualString
              right:
                value:
                  simple: Administrator
          root: inputs.Username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Set a value in context under the key you entered. If no value
        is entered, the script doesn't do anything.\n\nThis automation runs using
        the default Limited User role, unless you explicitly change the permissions.\nFor
        more information, see the section about permissions here:\n- For Cortex see
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      id: fe997579-a8cd-41b9-b329-cde85155044a
      iscommand: false
      name: Set users to reset password
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: fe997579-a8cd-41b9-b329-cde85155044a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1162,
          "y": 550
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: a5b17adf-9e17-4cac-a0e7-11d439ce5c8e
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: a5b17adf-9e17-4cac-a0e7-11d439ce5c8e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1502.5,
          "y": 1230
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: shadow_mode
          operator: isFalse
      label: "no"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "17"
      "no":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 44e5eec0-52ce-49fc-81f4-335b689e5a84
      iscommand: false
      name: Shadow Run?
      type: condition
      version: -1
    taskid: 44e5eec0-52ce-49fc-81f4-335b689e5a84
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1016.75,
          "y": 720
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          Shadow Mode: Active Directory Auto password reset
          Command: ad-expire-password
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: bb010c2b-a3c6-4e0d-8672-0f9399807d29
      iscommand: false
      name: Print To WarRoom
      script: Print
      type: regular
      version: -1
    taskid: bb010c2b-a3c6-4e0d-8672-0f9399807d29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 631,
          "y": 1060
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "8_3_#default#": 0.16,
      "9_3_#default#": 0.14
    },
    "paper": {
      "dimensions": {
        "height": 1250,
        "width": 1833.5,
        "x": 50,
        "y": 50
      }
    }
  }
